### PR TITLE
Fix typos in notebooks

### PR DESCRIPTION
**Pull request by pitmonticone**

### CODE REVIEW

**Review by udlbook — APPROVED** [review]

**Comment by pitmonticone** [comment]
Hi @udlbook, did you mean to merge the changes or close the pull request?

**Comment by udlbook** [comment]
I mean to merge them.  Sorry -- I barely use Github.  Can you do that now that I have "approved" them?

**Comment by udlbook** [comment]
Think that I've managed to do this now.

**Comment by pitmonticone** [comment]
Yes, now there correctly merged @udlbook. Thanks again for this resource!

**Pull request merged**
